plugins {
    id 'com.android.application'
}

android {
    namespace 'ir.avamedia.hamyarbuilding.a1'
    compileSdk 35

    defaultConfig {
        applicationId 'ir.avamedia.hamyarbuilding.a1'
        minSdk 21
        targetSdk 35
        versionCode 3
        versionName 'Alpha 2'
    }

    buildTypes {
        debug {
            minifyEnabled false
        }
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}
